# frozen_string_literal: true

source 'https://rubygems.org'

# Task runner [https://github.com/ruby/rake]
gem 'rake', '~> 13.0'

# Test runner [https://github.com/minitest/minitest]
gem 'minitest', '~> 5.16'

# Linting and formatting [https://github.com/rubocop/rubocop]
gem 'rubocop', '~> 1.79'
# Extra cops for Rakefiles [https://github.com/rubocop/rubocop-rake]
gem 'rubocop-rake', require: false
# Extra cops for minitest tests [https://github.com/rubocop/rubocop-minitest]
gem 'rubocop-minitest', require: false

# Type definitions [https://github.com/ruby/rbs]
gem 'rbs', '~> 3.0'

# Type checking for rbs [https://github.com/soutaro/steep]
gem 'steep', '~> 1.0'

# Coverage reports [https://github.com/simplecov-ruby/simplecov]
gem 'simplecov', require: false

# Doc generation [https://github.com/ruby/rdoc]
gem 'rdoc'

# Interactive Ruby shell for experimenting [https://github.com/ruby/irb]
gem 'irb'
